### ISSUE TITLE
before_update called even when no positioning columns are updated

### ISSUE THREAD

**Issue by creativetags** [brendon/positioning#12]
I'm assuming this is not intended to happen but it appears that the before_update callback is issued even when the positioning column wouldn't be touched. It creates a lot of unnecessary calls to the db.

https://github.com/brendon/positioning/blob/ead38ac95cabca002a16b69a32afef3e9c36eb20/lib/positioning.rb#L53C1-L54C1

**Comment by brendon** [comment]
Hi @creativetags, the callback always runs because we need to determine within there if the position or scope (or both) have changed and then react. If a position is actually assigned from parameters (even if it's the same value) we force `will_change` because it could be that the scope has changed and we coincidentally want to position the item in the new scope at the same position it was in in the old scope:

https://github.com/brendon/positioning/blob/ead38ac95cabca002a16b69a32afef3e9c36eb20/lib/positioning.rb#L42

Here's the code where we determine if we need to shuffle anything:

https://github.com/brendon/positioning/blob/ead38ac95cabca002a16b69a32afef3e9c36eb20/lib/positioning/mechanisms.rb#L22

Can you let me know a scenario where nothing changes (including you not just including the current `position` in your params) where any db calls are made?

**Comment by creativetags** [comment]
Ok, I misunderstood. Thanks for explaining

**Comment by brendon** [comment]
That's all good. Glad it wasn't anything serious :)
