### ISSUE TITLE
Migrating away from home grown code!

### ISSUE THREAD

**Issue by epugh** [brendon/positioning#2]
I steward https://github.com/o19s/quepid an open source tool.  We've had some home grown code for a million years, and recently when I upgraded some stuff, it "quit" working ;-).   It no longer preserves order of my `thecase.queries` with out some extra `thecase.reload`'s sprinkled about.   The code is here: https://github.com/o19s/quepid/tree/main/app/models/concerns/arrangement

For my existing users who have already sorted things using this database structure:
<img width="481" alt="image" src="https://github.com/brendon/positioning/assets/22395/7a5e2c8c-bafd-4a18-9751-37b6a3ccfd0c">

Could I just migrate the long integer values in the `arranged_at` column over to `position` and would this gem resort things the way it wants?   Or do I need to manually sort things 1,2,3,4 etc in my migration?   Or other suggestions on how to migrate?  

It's not a critical migration, if people lose their sorting, well oh well, but it would be nice!

**Comment by brendon** [comment]
Good question :) at the moment there’s no fault tolerance to the code so it won’t fix gaps between positioned items and nor will it normalise the values other than to clamp them between 1 and the MAX of the current items.

I think it would be best to run a migration that just walks over every list (by scope, ordered by the existing positions) and explicitly update (use `update_all` to avoid callbacks) the positions to follow a 1..MAX sequence with no gaps before letting your users loose on the lists. You can do this in a migration as you deploy the `positioned` gem for the first time. I would stop access to the app via your web server for this just to ensure it migrates nicely and you don’t get any interference.

I think there’s some example code for this on the ActAsList readme but let me know if you get stuck.

I’m super keen to hear how you find the gem so keep me posted :)

**Comment by brendon** [comment]
It looks like your list code is akin to `ranked-model`. There is a big drawback with the sparse list concept in that it requires rebalancing quite frequently if you mostly append or prepend to the list because you run out of space between the first or last item and the min or max values. I maintain that gem too lol!

If you have a look in the `Mechanisims` class for this gem you’ll see we do some potentially expensive updates when expanding or contracting space in the list. We updated those items in the way to have a negative version of their current position. Then update them again to be positive with an increment in one or the other direction. This is the work around not being able to update items in a set order easily with one update statement. It’d be interesting to see how that performs with a large dataset like yours.

**Comment by brendon** [comment]
Closing this for now @epugh. Here's the documentation I was mentioning:

https://github.com/brendon/acts_as_list?tab=readme-ov-file#adding-acts_as_list-to-an-existing-model
