### ISSUE TITLE
Positioning element fails when uniqueness constraint has a matching model validation

### ISSUE THREAD

**Issue by difernandez** [brendon/positioning#21]
When I have a positioned model on a list, with a database constraint accompanied by a uniqueness model validation, something like this:

```ruby
class Item
	belongs_to :list
	
	validates :position, uniqueness: { scope: [:list_id] }	
	
	positioned on: :list
end

#  Indexes
#  index_items_on_position_and_list_id  (position,list_id) UNIQUE
```

Positioning fails whan updating an item with a position that's taken on the target list, failing on the model validation, "position is taken". Is this by design perhaps? I see that [the callbacks](https://github.com/brendon/positioning/blob/main/lib/positioning.rb#L53) are defined as `before_(update|create)` which go after validations. Would there be a problem if they were done before validations?
If there is a problem or it's a design decision of this gem, would you consider adding a note on the README regarding model uniqueness validations maybe?

Thanks for your work on the gem btw!

**Comment by brendon** [comment]
Hi @difernandez, that's an interesting one :) I haven't ever worried about adding a validation on the `position` column because we recommend a unique (in scope) index at the database level and a NOT NULL constraint there also.

I guess the problem with moving the callbacks to before validation would be that they mutate the database and so a casual call to `.valid?` would do damage potentially, or at least execute your intention before you expect it to.

Let me know that you think :)

**Comment by brendon** [comment]
Actually, as I think about it more, we could move the `solidify_position` call to before validation so that it has a valid value prior to saving. There are some calls before that that I'd need to check still work but it could work out as a good solution. I'll have a look at it today and see what I can come up with :)

**Comment by brendon** [comment]
I've looked into this further and am not quite happy with solidifying the position on validation as this step can happen outside the scope of a create or update. It also means that it happens outside of the advisory lock, so we can't guarantee that the solidified position is what we really want (race conditions). I've committed the change to a branch for you to play with:

https://github.com/brendon/positioning/tree/solidify-on-validate

At this stage I don't think I'll take it any further as it messes with the fundamentals of how this library work. It's designed to atomically shuffle things around to maintain a list with no gaps in it etc...

**Comment by difernandez** [comment]
Maybe you could limit it to the scope of a create or update using `on:`, like `before_validation { Mechanisms.new(self, column).solidify_position }, on: [:create, :update]`? But I guess that wouldn't address the issue of it being outside of the advisory lock. I understand not taking it any further, thanks for looking into it though!

**Comment by brendon** [comment]
I just tested that out and you're right, it still occurs outside the advisory lock.

As I think about it more, a record is indeed valid at the model level with a `nil` position value in terms of the `positioning` gem as that means "at the end of the list". The database needs to enforce `NOT NULL` but not the model. That might help you reason about removing the validation :D

Thank you for raising this, as I'm sure it'll help others in the future, and it was worthwhile thinking it through myself too :D
