### ISSUE TITLE
Undefined method + for nil

### ISSUE THREAD

**Issue by bendangelo** [brendon/positioning#30]
Hi, it looks like when destroying records with a nil position causes this error.

```
error_class: NoMethodError
message: "undefined method `+' for nil"
backtrace: ["/home/bendangelo/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/positioning-0.4.2/lib/positioning/mechanisms.rb:49:in `destroy_position'", "/home/bendangelo/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/positioning-0.4.2/lib/positioning.rb:55:in `block in positioned'", 
```

**Comment by brendon** [comment]
Hi @bendangelo, yes the assumption is that all records in the table have a position. You should heal your table first if you’re starting with pre-existing records. There’s some instructions in the readme :)

**Comment by brendon** [comment]
No not yet I don't think. Will have to add it to the matrix :)

**Comment by brendon** [comment]
I'm not seeing an errors with the tests. Are you able to dig in a bit more and figure out the root cause? We can then write a test that fails :)

**Comment by bendangelo** [comment]
So it's not the ruby version or the rails version. I can't reproduce this locally, it only happens on production. I have no idea what's going on.

I now noticed I'm getting this error in my specs:
```
RuntimeError: Locking a record with unpersisted changes is not supported. Use `save` to persist the changes, or `reload` to discard them explicitly. Changed attributes: "a", "b".
from /home/bendangelo/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/activerecord-8.0.0/lib/active_record/locking/pessimistic.rb:72:in `lock!'
```

I corrected the positioned call by adding a column. The code goes like this:
```
# model
  positioned on: :list, column: :position

# spec
      list.items << build(:item, value: nil)

      list.save!
```

It doesn't like the `<< build` line. Sorry I don't know much about the internals.

**Comment by bendangelo** [comment]
Hey after further testing. I figured out the issue was the positioned call did not have any column assigned. I thought it would default to `position` but it does not. After adding that I'm now getting the lock error above.

**Comment by brendon** [comment]
Thanks for working on this @bendangelo. The locked error is going to be because your testing is building a parent record and then also creating or destroying child records. We lock the parent scope and so if this doesn't existing the database or it has unpersisted changes you'd need to alter the tests to cope with that.

If it's a legitimate use case to try to delete a child with a parent that has unpersisted changes then I guess I'm open to looking at catering for that.

You could just do `list.items.build(value: nil)` or `.create`. Check out our test suite for how we do it with minutest.

The default column is `position` and it should be being set. I wonder if you have something funky going on with this model that's overriding something? You don't have a default value for the `position` column do you? That wouldn't work.

I think the next step would be for you to create a PR with a failing test in our test suite and I can then isolate where things are going wrong :)

**Comment by bendangelo** [comment]
There is no default value in that column. I just want to point out the readme says the default column name is `positioned`, I'm not sure if that's a typo.

I think it'll be good if the library cannot find the column it outputs some sort of warning. That will prevent this original error from happening.

As for the spec it can be changed. I just wasn't sure if you knew about that.

**Comment by scart88** [comment]
For some reason the position_was is set to nil somewhere in the code. 

I attached a few screenshots.

Here is what I have in my model:
`positioned on: [:item, :item_version_id, :kind, :setting_type], column: :position`

This happens when I'm trying to remove a record.

![Image](https://github.com/user-attachments/assets/7e3501a9-9aa0-4cf7-a5e0-859526f55171)

![Image](https://github.com/user-attachments/assets/89cec722-22d2-408c-b099-f3b4c041af57)

![Image](https://github.com/user-attachments/assets/ae6d102a-952c-4a30-a998-99613a85e847)

![Image](https://github.com/user-attachments/assets/38ddd698-f8c4-4fd6-9036-fab8ce22354e)

**Comment by brendon** [comment]
Double-check that you're defining the `belongs_to :item` earlier in the code than your call to `positioned`. Someone had the same problem a few days ago.

**Comment by brendon** [comment]
Also, create a new issue if that doesn't fix the issue :)

**Comment by scart88** [comment]
Thank you very much for your help. I created a new issues #39 as the error persisted
