### ISSUE TITLE
Presence validation results in errors when using implicit position

### ISSUE THREAD

**Issue by scottkacyn** [brendon/positioning#33]
I have the following validation on the `position` column:
```
validates :position, presence: true, uniqueness: { scope: %i[bucket_id parent_id] }
```

When I use explicit position (ie. `position: 1`) everything works as expected. However, if I try to use implicit positioning via `position: nil` or `position: :first`, my validation fails with "Position can't be blank". I am leaving the `presence: true` validation off for now, but it would be great to be able to include it along with the database constraint.

**Comment by brendon** [comment]
Hi @scottkacyn, unfortunately because we solidify the position on create and update as part of a record lock you can’t use a validation on the position column. It might help to think of the position column as a black box managed by the gem. You can set it if you want, but if you don’t it’ll always be set anyway unless you skip callbacks. The database restraint is still a good idea though.

What was your reasoning behind wanting to show a validation error to the user?

**Comment by brendon** [comment]
@scottkacyn, did you want to discuss this more?

**Comment by scottkacyn** [comment]
@brendon sorry for not replying here, I have notifications disabled for GH so missed your follow up. I think it's ok to avoid this work for now. Thank you for creating the gem, it's been working great for us!

**Comment by brendon** [comment]
That's all good :) Great to hear things have been working well :D
